import type { Rune } from "@/lib/types";

/**
 * The 33 runes.
 *
 * Source: The Arreat Summit (Blizzard's own official strategy site) — rune
 * property table and Horadric Cube recipe list. Rune properties and required
 * levels have been stable since 1.10 and are unchanged in D2R.
 * See `docs/research/01-runes.md`.
 *
 * `armorMod` covers body armor and helms. `shieldMod` is split out because
 * roughly a third of runes behave differently in shields, and that difference
 * is exactly the kind of thing players get wrong.
 */
export const runes: Rune[] = [
  {
    slug: "el",
    name: "El",
    number: 1,
    requiredLevel: 11,
    summary: "The lowest rune. Attack rating and light radius.",
    weaponMod: "+50 to Attack Rating, +1 Light Radius",
    armorMod: "+15 Defense, +1 to Light Radius",
    helmMod: "+15 Defense, +1 to Light Radius",
    shieldMod: "+15 Defense, +1 to Light Radius",
    upgradeRecipe: "3 x El = Eld",
    farmNotes: "Drops everywhere from Normal onwards. Never worth hunting.",
  },
  {
    slug: "eld",
    name: "Eld",
    number: 2,
    requiredLevel: 11,
    summary: "Anti-undead damage; blocking on shields.",
    weaponMod: "+75% Damage to Undead, +50 Attack Rating against Undead",
    armorMod: "15% Slower Stamina Drain",
    helmMod: "15% Slower Stamina Drain",
    shieldMod: "7% Increased Chance of Blocking",
    upgradeRecipe: "3 x Eld = Tir",
    farmNotes: "Extremely common. Used in Stealth and Steel.",
  },
  {
    slug: "tir",
    name: "Tir",
    number: 3,
    requiredLevel: 13,
    summary: "Mana after each kill — the early caster's sustain rune.",
    weaponMod: "+2 to Mana after each Kill",
    armorMod: "+2 to Mana after each Kill",
    helmMod: "+2 to Mana after each Kill",
    shieldMod: "+2 to Mana after each Kill",
    upgradeRecipe: "3 x Tir = Nef",
    farmNotes: "Very common. Half of Stealth.",
  },
  {
    slug: "nef",
    name: "Nef",
    number: 4,
    requiredLevel: 13,
    summary: "Knockback on weapons, missile defense on armor.",
    weaponMod: "Knockback",
    armorMod: "+30 Defense vs. Missile",
    helmMod: "+30 Defense vs. Missile",
    shieldMod: "+30 Defense vs. Missile",
    upgradeRecipe: "3 x Nef = Eth",
    farmNotes: "Very common. Half of Stealth.",
  },
  {
    slug: "eth",
    name: "Eth",
    number: 5,
    requiredLevel: 15,
    summary: "Target defense reduction; mana regeneration on armor.",
    weaponMod: "-25% to Target Defense",
    armorMod: "Regenerate Mana 15%",
    helmMod: "Regenerate Mana 15%",
    shieldMod: "Regenerate Mana 15%",
    upgradeRecipe: "3 x Eth = Ith",
    farmNotes: "Very common. Used in Insight and Spirit.",
  },
  {
    slug: "ith",
    name: "Ith",
    number: 6,
    requiredLevel: 15,
    summary: "Maximum damage; damage-to-mana on armor.",
    weaponMod: "+9 to Maximum Damage",
    armorMod: "15% Damage Taken Goes to Mana",
    helmMod: "15% Damage Taken Goes to Mana",
    shieldMod: "15% Damage Taken Goes to Mana",
    upgradeRecipe: "3 x Ith = Tal",
    farmNotes: "Very common. Used in Insight and Malice.",
  },
  {
    slug: "tal",
    name: "Tal",
    number: 7,
    requiredLevel: 17,
    summary: "Poison damage; poison resistance on armor.",
    weaponMod: "+75 Poison Damage over 5 seconds",
    armorMod: "Poison Resist +30%",
    helmMod: "Poison Resist +30%",
    shieldMod: "Poison Resist +35%",
    upgradeRecipe: "3 x Tal = Ral",
    farmNotes: "Common. First rune of Stealth and Ancient's Pledge.",
  },
  {
    slug: "ral",
    name: "Ral",
    number: 8,
    requiredLevel: 19,
    summary: "Fire damage; fire resistance on armor. Also repairs armor in the Cube.",
    weaponMod: "Adds 5-30 Fire Damage",
    armorMod: "Fire Resist +30%",
    helmMod: "Fire Resist +30%",
    shieldMod: "Fire Resist +35%",
    upgradeRecipe: "3 x Ral = Ort",
    farmNotes:
      "Common. Countess drops it readily. Cube with an armor piece to fully repair it.",
  },
  {
    slug: "ort",
    name: "Ort",
    number: 9,
    requiredLevel: 21,
    summary:
      "Lightning damage; lightning resistance on armor. Repairs weapons in the Cube.",
    weaponMod: "Adds 1-50 Lightning Damage",
    armorMod: "Lightning Resist +30%",
    helmMod: "Lightning Resist +30%",
    shieldMod: "Lightning Resist +35%",
    upgradeRecipe: "3 x Ort = Thul",
    farmNotes:
      "Common. Used in Lore and Ancient's Pledge. Cube with a weapon to fully repair it.",
  },
  {
    slug: "thul",
    name: "Thul",
    number: 10,
    requiredLevel: 23,
    summary: "Cold damage; cold resistance on armor.",
    weaponMod: "Adds 3-14 Cold Damage (3 second duration)",
    armorMod: "Cold Resist +30%",
    helmMod: "Cold Resist +30%",
    shieldMod: "Cold Resist +35%",
    upgradeRecipe: "3 x Thul + 1 Chipped Topaz = Amn",
    farmNotes: "Common from the Countess in Normal. Used in Ancient's Pledge.",
  },
  {
    slug: "amn",
    name: "Amn",
    number: 11,
    requiredLevel: 25,
    summary: "Life steal — the single most important low rune for melee.",
    weaponMod: "7% Life Stolen per Hit",
    armorMod: "Attacker Takes Damage of 14",
    helmMod: "Attacker Takes Damage of 14",
    shieldMod: "Attacker Takes Damage of 14",
    upgradeRecipe: "3 x Amn + 1 Chipped Amethyst = Sol",
    farmNotes:
      "Countess in Nightmare, and any level 25+ area. Life steal makes it disproportionately valuable early.",
  },
  {
    slug: "sol",
    name: "Sol",
    number: 12,
    requiredLevel: 27,
    summary: "Minimum damage; flat damage reduction on armor.",
    weaponMod: "+9 to Minimum Damage",
    armorMod: "Damage Reduced by 7",
    helmMod: "Damage Reduced by 7",
    shieldMod: "Damage Reduced by 7",
    upgradeRecipe: "3 x Sol + 1 Chipped Sapphire = Shael",
    farmNotes: "Countess in Nightmare. Used in Insight and Rhyme.",
  },
  {
    slug: "shael",
    name: "Shael",
    number: 13,
    requiredLevel: 29,
    summary:
      "20 IAS on weapons, 20 FHR on armor, 20 FBR on shields. Three different jobs.",
    weaponMod: "20% Increased Attack Speed",
    armorMod: "20% Faster Hit Recovery",
    helmMod: "20% Faster Hit Recovery",
    shieldMod: "20% Faster Block Rate",
    upgradeRecipe: "3 x Shael + 1 Chipped Ruby = Dol",
    farmNotes:
      "Countess in Nightmare. Always keep spares — it hits three different breakpoint tables.",
  },
  {
    slug: "dol",
    name: "Dol",
    number: 14,
    requiredLevel: 31,
    summary: "Causes monsters to flee; life replenish on armor.",
    weaponMod: "Hit Causes Monster to Flee 25%",
    armorMod: "Replenish Life +7",
    helmMod: "Replenish Life +7",
    shieldMod: "Replenish Life +7",
    upgradeRecipe: "3 x Dol + 1 Chipped Emerald = Hel",
    farmNotes:
      "Countess in Nightmare. Flee is usually a downside — read the runeword before socketing.",
  },
  {
    slug: "hel",
    name: "Hel",
    number: 15,
    requiredLevel: 0,
    summary:
      "Requirement reduction, and the only rune with no level requirement. Also removes sockets.",
    weaponMod: "Requirements -20%",
    armorMod: "Requirements -15%",
    helmMod: "Requirements -15%",
    shieldMod: "Requirements -15%",
    upgradeRecipe: "3 x Hel + 1 Chipped Diamond = Io",
    farmNotes:
      "Cube a Hel rune with a Scroll of Town Portal to empty an item's sockets. The socketed items are destroyed, the base survives.",
  },
  {
    slug: "io",
    name: "Io",
    number: 16,
    requiredLevel: 35,
    summary: "+10 Vitality in any slot.",
    weaponMod: "+10 to Vitality",
    armorMod: "+10 to Vitality",
    helmMod: "+10 to Vitality",
    shieldMod: "+10 to Vitality",
    upgradeRecipe: "3 x Io + 1 Flawed Topaz = Lum",
    farmNotes: "Countess in Hell, or any level 35+ area.",
  },
  {
    slug: "lum",
    name: "Lum",
    number: 17,
    requiredLevel: 37,
    summary: "+10 Energy in any slot.",
    weaponMod: "+10 to Energy",
    armorMod: "+10 to Energy",
    helmMod: "+10 to Energy",
    shieldMod: "+10 to Energy",
    upgradeRecipe: "3 x Lum + 1 Flawed Amethyst = Ko",
    farmNotes: "Countess in Hell. Used in Smoke and Wealth.",
  },
  {
    slug: "ko",
    name: "Ko",
    number: 18,
    requiredLevel: 39,
    summary: "+10 Dexterity in any slot.",
    weaponMod: "+10 to Dexterity",
    armorMod: "+10 to Dexterity",
    helmMod: "+10 to Dexterity",
    shieldMod: "+10 to Dexterity",
    upgradeRecipe: "3 x Ko + 1 Flawed Sapphire = Fal",
    farmNotes: "Countess in Hell. Used in Lionheart and Duress.",
  },
  {
    slug: "fal",
    name: "Fal",
    number: 19,
    requiredLevel: 41,
    summary: "+10 Strength in any slot.",
    weaponMod: "+10 to Strength",
    armorMod: "+10 to Strength",
    helmMod: "+10 to Strength",
    shieldMod: "+10 to Strength",
    upgradeRecipe: "3 x Fal + 1 Flawed Ruby = Lem",
    farmNotes: "Countess in Hell. Used in Lionheart and Chains of Honor.",
  },
  {
    slug: "lem",
    name: "Lem",
    number: 20,
    requiredLevel: 43,
    summary: "Extra gold find. The Wealth rune.",
    weaponMod: "75% Extra Gold from Monsters",
    armorMod: "50% Extra Gold from Monsters",
    helmMod: "50% Extra Gold from Monsters",
    shieldMod: "50% Extra Gold from Monsters",
    upgradeRecipe: "3 x Lem + 1 Flawed Emerald = Pul",
    farmNotes:
      "Countess in Hell. The last rune in the cheap 3-to-1 upgrade chain — from Pul upward the ratio improves to 2-to-1.",
  },
  {
    slug: "pul",
    name: "Pul",
    number: 21,
    requiredLevel: 45,
    summary: "Anti-demon damage; enhanced defense on armor.",
    weaponMod: "+75% Damage to Demons, +100 Attack Rating against Demons",
    armorMod: "+30% Enhanced Defense",
    helmMod: "+30% Enhanced Defense",
    shieldMod: "+30% Enhanced Defense",
    upgradeRecipe: "2 x Pul + 1 Flawed Diamond = Um",
    farmNotes:
      "Countess in Hell, Lower Kurast chests, Travincal. The first of the mid runes.",
  },
  {
    slug: "um",
    name: "Um",
    number: 22,
    requiredLevel: 47,
    summary: "Open Wounds; +15 all resistances on armor, +22 on shields.",
    weaponMod: "25% Chance of Open Wounds",
    armorMod: "All Resistances +15",
    helmMod: "All Resistances +15",
    shieldMod: "All Resistances +22",
    upgradeRecipe: "2 x Um + 1 Topaz = Mal",
    farmNotes:
      "Countess in Hell, Lower Kurast, Travincal, The Pit. A genuinely useful socket filler in its own right.",
  },
  {
    slug: "mal",
    name: "Mal",
    number: 23,
    requiredLevel: 49,
    summary: "Prevent Monster Heal; magic damage reduction on armor.",
    weaponMod: "Prevent Monster Heal",
    armorMod: "Magic Damage Reduced by 7",
    helmMod: "Magic Damage Reduced by 7",
    shieldMod: "Magic Damage Reduced by 7",
    upgradeRecipe: "2 x Mal + 1 Amethyst = Ist",
    farmNotes: "Countess in Hell is the highest rune she can drop. Also Travincal and The Pit.",
  },
  {
    slug: "ist",
    name: "Ist",
    number: 24,
    requiredLevel: 51,
    summary: "The magic find rune. 30% MF on weapons, 25% elsewhere.",
    weaponMod: "30% Better Chance of Getting Magic Items",
    armorMod: "25% Better Chance of Getting Magic Items",
    helmMod: "25% Better Chance of Getting Magic Items",
    shieldMod: "25% Better Chance of Getting Magic Items",
    upgradeRecipe: "2 x Ist + 1 Sapphire = Gul",
    farmNotes:
      "Above the Countess's cap. Travincal, The Pit, Ancient Tunnels, Chaos Sanctuary, Terror Zones.",
  },
  {
    slug: "gul",
    name: "Gul",
    number: 25,
    requiredLevel: 53,
    summary: "Attack rating; +5% max poison resist on armor.",
    weaponMod: "+20% Bonus to Attack Rating",
    armorMod: "+5% to Maximum Poison Resist",
    helmMod: "+5% to Maximum Poison Resist",
    shieldMod: "+5% to Maximum Poison Resist",
    upgradeRecipe: "2 x Gul + 1 Ruby = Vex",
    farmNotes: "Travincal, The Pit, Chaos Sanctuary, high Terror Zones.",
  },
  {
    slug: "vex",
    name: "Vex",
    number: 26,
    requiredLevel: 55,
    summary: "Mana steal; +5% max fire resist on armor.",
    weaponMod: "7% Mana Stolen per Hit",
    armorMod: "+5% to Maximum Fire Resist",
    helmMod: "+5% to Maximum Fire Resist",
    shieldMod: "+5% to Maximum Fire Resist",
    upgradeRecipe: "2 x Vex + 1 Emerald = Ohm",
    farmNotes: "High rune territory. Travincal, Chaos Sanctuary, Worldstone Keep, Terror Zones.",
  },
  {
    slug: "ohm",
    name: "Ohm",
    number: 27,
    requiredLevel: 57,
    summary: "+50% enhanced damage; +5% max cold resist on armor.",
    weaponMod: "+50% Enhanced Damage",
    armorMod: "+5% to Maximum Cold Resist",
    helmMod: "+5% to Maximum Cold Resist",
    shieldMod: "+5% to Maximum Cold Resist",
    upgradeRecipe: "2 x Ohm + 1 Diamond = Lo",
    farmNotes: "High rune. Travincal, Chaos Sanctuary, Worldstone Keep, Terror Zones.",
  },
  {
    slug: "lo",
    name: "Lo",
    number: 28,
    requiredLevel: 59,
    summary: "Deadly Strike; +5% max lightning resist on armor.",
    weaponMod: "20% Deadly Strike",
    armorMod: "+5% to Maximum Lightning Resist",
    helmMod: "+5% to Maximum Lightning Resist",
    shieldMod: "+5% to Maximum Lightning Resist",
    upgradeRecipe: "2 x Lo + 1 Flawless Topaz = Sur",
    farmNotes: "High rune. Needed for Grief, Fortitude and Infinity.",
  },
  {
    slug: "sur",
    name: "Sur",
    number: 29,
    requiredLevel: 61,
    summary: "Blinds target; maximum mana on armor, +50 mana on shields.",
    weaponMod: "Hit Blinds Target",
    armorMod: "Maximum Mana 5%",
    helmMod: "Maximum Mana 5%",
    shieldMod: "+50 to Mana",
    upgradeRecipe: "2 x Sur + 1 Flawless Amethyst = Ber",
    farmNotes: "High rune. Needed for Infinity and Heart of the Oak.",
  },
  {
    slug: "ber",
    name: "Ber",
    number: 30,
    requiredLevel: 63,
    summary:
      "Crushing Blow on weapons, and 8% damage reduction on armor — the defining defensive rune.",
    weaponMod: "20% Chance of Crushing Blow",
    armorMod: "Damage Reduced by 8%",
    helmMod: "Damage Reduced by 8%",
    shieldMod: "Damage Reduced by 8%",
    upgradeRecipe: "2 x Ber + 1 Flawless Sapphire = Jah",
    farmNotes:
      "Top-tier. Needed for Infinity, Enigma, Call to Arms and Fortitude. One of the two most in-demand runes in the game.",
  },
  {
    slug: "jah",
    name: "Jah",
    number: 31,
    requiredLevel: 65,
    summary:
      "Ignore Target's Defense; +5% maximum life on armor, +50 life on shields.",
    weaponMod: "Ignore Target's Defense",
    armorMod: "Increase Maximum Life 5%",
    helmMod: "Increase Maximum Life 5%",
    shieldMod: "+50 to Life",
    upgradeRecipe: "2 x Jah + 1 Flawless Ruby = Cham",
    farmNotes: "Top-tier. Needed for Enigma and Call to Arms.",
  },
  {
    slug: "cham",
    name: "Cham",
    number: 32,
    requiredLevel: 67,
    summary: "Freezes target; Cannot Be Frozen on armor.",
    weaponMod: "Freeze Target +3",
    armorMod: "Cannot Be Frozen",
    helmMod: "Cannot Be Frozen",
    shieldMod: "Cannot Be Frozen",
    upgradeRecipe: "2 x Cham + 1 Flawless Emerald = Zod",
    farmNotes:
      "Cannot Be Frozen in a helm is a real solution when your armor slot is occupied by a runeword that lacks it.",
  },
  {
    slug: "zod",
    name: "Zod",
    number: 33,
    requiredLevel: 69,
    summary: "Indestructible. The rarest rune in the game.",
    weaponMod: "Indestructible",
    armorMod: "Indestructible",
    helmMod: "Indestructible",
    shieldMod: "Indestructible",
    farmNotes:
      "The rarest drop in D2. Its main practical use is making an ethereal item permanent — but check whether a cheaper repair option exists first.",
  },
];
