import type { Skill, SkillTree } from "@/lib/types";

/**
 * The Sorceress's three skill trees and thirty skills.
 *
 * Skill names and unlock levels verified against The Arreat Summit's Sorceress
 * skill pages. Synergy percentages verified against current build guides
 * (Maxroll, D2Runewizard, DiabloBytes) — see `docs/research/04-sorceress.md`.
 */

export const sorceressTrees: SkillTree[] = [
  {
    slug: "cold-spells",
    name: "Cold Spells",
    classSlug: "sorceress",
    order: 1,
    summary: "Freezing, slowing and the game's premier magic-find damage skill.",
    theme:
      "Cold does less raw damage than fire or lightning, but it freezes and chills, which is defence. Blizzard is the safest strong farming skill in the game.",
  },
  {
    slug: "lightning-spells",
    name: "Lightning Spells",
    classSlug: "sorceress",
    order: 2,
    summary: "The highest damage ceiling, plus Teleport and Static Field.",
    theme:
      "Enormous damage spread over a huge range, and the tree that holds Teleport — which every Sorceress takes regardless of build.",
  },
  {
    slug: "fire-spells",
    name: "Fire Spells",
    classSlug: "sorceress",
    order: 3,
    summary: "Sustained area damage, and the Warmth mana engine.",
    theme:
      "Consistent area damage over time. Weakest early, but Fire Ball and Meteor together clear well, and Warmth is taken by nearly every Sorceress.",
  },
];

export const sorceressSkills: Skill[] = [
  // -------------------------------------------------------------------------
  // Cold
  // -------------------------------------------------------------------------
  {
    slug: "ice-bolt",
    name: "Ice Bolt",
    classSlug: "sorceress",
    tree: "cold-spells",
    kind: "spell",
    element: "cold",
    requiredLevel: 1,
    summary: "A single freezing bolt. Weak on its own, but a Blizzard synergy worth 20 points.",
    synergyFor: ["blizzard", "frozen-orb", "ice-blast", "glacial-spike"],
    mechanics: [
      "On a Blizzard build you will max this and never cast it — it exists purely as a +5% per level synergy.",
    ],
    confidence: "verified",
  },
  {
    slug: "frozen-armor",
    name: "Frozen Armor",
    classSlug: "sorceress",
    tree: "cold-spells",
    kind: "buff",
    element: "cold",
    requiredLevel: 1,
    summary: "Defence bonus, and freezes melee attackers that hit you.",
    mechanics: [
      "Only one cold armor can be active at a time — Frozen, Shiver and Chilling are mutually exclusive.",
      "Frozen Armor gives the least defence of the three but freezes attackers, which is usually the more useful effect.",
    ],
    confidence: "verified",
  },
  {
    slug: "frost-nova",
    name: "Frost Nova",
    classSlug: "sorceress",
    tree: "cold-spells",
    kind: "spell",
    element: "cold",
    requiredLevel: 6,
    summary: "An expanding ring of cold centred on you. Good crowd control, poor damage.",
    confidence: "verified",
  },
  {
    slug: "ice-blast",
    name: "Ice Blast",
    classSlug: "sorceress",
    tree: "cold-spells",
    kind: "spell",
    element: "cold",
    requiredLevel: 6,
    prerequisites: ["ice-bolt"],
    summary: "A stronger single-target bolt that fully freezes. Blizzard synergy and a usable filler.",
    synergies: [{ skill: "ice-bolt", bonus: "+damage per level" }],
    synergyFor: ["blizzard", "frozen-orb", "glacial-spike"],
    mechanics: [
      "Unlike most cold skills it *freezes* rather than chills, which stops a dangerous monster outright.",
      "Worth casting during Blizzard's cooldown against single targets.",
    ],
    confidence: "verified",
  },
  {
    slug: "shiver-armor",
    name: "Shiver Armor",
    classSlug: "sorceress",
    tree: "cold-spells",
    kind: "buff",
    element: "cold",
    requiredLevel: 12,
    prerequisites: ["frozen-armor", "ice-blast"],
    summary: "More defence than Frozen Armor; damages melee attackers instead of freezing them.",
    confidence: "verified",
  },
  {
    slug: "glacial-spike",
    name: "Glacial Spike",
    classSlug: "sorceress",
    tree: "cold-spells",
    kind: "spell",
    element: "cold",
    requiredLevel: 18,
    prerequisites: ["ice-blast"],
    summary:
      "An exploding ice projectile that freezes a small area. The Blizzard build's crowd control and its second-largest synergy.",
    synergies: [{ skill: "ice-bolt", bonus: "+damage per level" }],
    synergyFor: ["blizzard"],
    mechanics: [
      "Freezes everything in the blast radius, which is why a Blizzard Sorceress rarely gets hit.",
      "This is what you cast while Blizzard is on cooldown.",
    ],
    confidence: "verified",
  },
  {
    slug: "blizzard",
    name: "Blizzard",
    classSlug: "sorceress",
    tree: "cold-spells",
    kind: "spell",
    element: "cold",
    requiredLevel: 24,
    prerequisites: ["frost-nova", "glacial-spike"],
    summary:
      "A storm of ice shards over a wide area. The best magic-find farming skill in the game.",
    synergies: [
      { skill: "ice-bolt", bonus: "+5% damage per level" },
      { skill: "ice-blast", bonus: "+5% damage per level" },
      { skill: "glacial-spike", bonus: "+5% damage per level" },
    ],
    manaCost: "Moderate, and unchanged by the cooldown — mana is rarely the limiter.",
    mechanics: [
      "Has a hard cooldown that cannot be reduced by Faster Cast Rate or anything else.",
      "Overlapping Blizzards stack — two casts covering the same ground deal both lots of damage.",
      "Cast it *ahead* of moving enemies so they walk into the area, rather than on top of them.",
    ],
    confidence: "verified",
  },
  {
    slug: "chilling-armor",
    name: "Chilling Armor",
    classSlug: "sorceress",
    tree: "cold-spells",
    kind: "buff",
    element: "cold",
    requiredLevel: 24,
    prerequisites: ["shiver-armor"],
    summary: "Highest defence of the three armors; retaliates against ranged attackers only.",
    mechanics: [
      "Responds to ranged attacks, not melee. Pick it when the threat is arrows and bolts.",
    ],
    confidence: "verified",
  },
  {
    slug: "frozen-orb",
    name: "Frozen Orb",
    classSlug: "sorceress",
    tree: "cold-spells",
    kind: "spell",
    element: "cold",
    requiredLevel: 30,
    prerequisites: ["blizzard"],
    summary:
      "A slow-travelling orb that sprays ice bolts in all directions. Excellent area coverage, no cooldown.",
    synergies: [
      { skill: "ice-bolt", bonus: "+damage per level" },
      { skill: "ice-blast", bonus: "+damage per level" },
    ],
    mechanics: [
      "No cooldown, unlike Blizzard, so it fits a more aggressive playstyle.",
      "Damage is spread across many small bolts, which makes it weaker on single targets and stronger on packs.",
    ],
    confidence: "verified",
  },
  {
    slug: "cold-mastery",
    name: "Cold Mastery",
    classSlug: "sorceress",
    tree: "cold-spells",
    kind: "passive",
    element: "cold",
    requiredLevel: 30,
    summary:
      "Lowers enemy cold resistance. The largest damage multiplier available to any cold build.",
    mechanics: [
      "Against non-immune monsters it subtracts directly from their cold resistance, and can push it negative.",
      "Against cold-*immune* monsters it works at one fifth effectiveness and cannot break the immunity.",
      "Because +skills raise it, most builds put fewer hard points here than the 20 the tooltip suggests — level 17 after gear is a common target.",
    ],
    confidence: "verified",
  },

  // -------------------------------------------------------------------------
  // Lightning
  // -------------------------------------------------------------------------
  {
    slug: "charged-bolt",
    name: "Charged Bolt",
    classSlug: "sorceress",
    tree: "lightning-spells",
    kind: "spell",
    element: "lightning",
    requiredLevel: 1,
    summary: "A spray of short-range bolts. Strong at point-blank range, weak at distance.",
    synergyFor: ["nova", "lightning", "chain-lightning"],
    confidence: "verified",
  },
  {
    slug: "static-field",
    name: "Static Field",
    classSlug: "sorceress",
    tree: "lightning-spells",
    kind: "spell",
    element: "lightning",
    requiredLevel: 6,
    summary:
      "Removes 25% of the current life of everything nearby. Works on bosses, and scales with nothing.",
    manaCost: "Low — 9 mana at all levels",
    mechanics: [
      "Deals 25% of the target's **current** life, not maximum life. Repeated casts therefore have sharply diminishing effect.",
      "It has a floor: it will not reduce a monster below **33% life in Nightmare** or **50% life in Hell**. There is no floor in Normal.",
      "Skill points only increase its **radius**, never its potency. One point is enough for almost every build.",
      "Sources disagree on whether enemy Lightning Resistance reduces it — see the mechanics page. Treat it as a softening tool for your mercenary, not as a reliable answer to immunity.",
    ],
    confidence: "community",
  },
  {
    slug: "telekinesis",
    name: "Telekinesis",
    classSlug: "sorceress",
    tree: "lightning-spells",
    kind: "spell",
    element: "magic",
    requiredLevel: 6,
    summary:
      "Picks up items and operates objects at range, and knocks back enemies. Also the Teleport prerequisite.",
    mechanics: [
      "Every Sorceress takes one point purely because Teleport requires it.",
      "It opens chests and picks up potions from across the screen, which is a genuine quality-of-life gain.",
      "The knockback and brief stun buy time against a dangerous monster.",
    ],
    confidence: "verified",
  },
  {
    slug: "nova",
    name: "Nova",
    classSlug: "sorceress",
    tree: "lightning-spells",
    kind: "spell",
    element: "lightning",
    requiredLevel: 12,
    prerequisites: ["static-field"],
    summary: "An expanding ring of lightning centred on you. The core of the Nova build.",
    synergies: [
      { skill: "charged-bolt", bonus: "+damage per level" },
      { skill: "lightning", bonus: "+damage per level" },
    ],
    confidence: "verified",
  },
  {
    slug: "lightning",
    name: "Lightning",
    classSlug: "sorceress",
    tree: "lightning-spells",
    kind: "spell",
    element: "lightning",
    requiredLevel: 12,
    prerequisites: ["charged-bolt"],
    summary: "A bolt that strikes instantly across the whole screen.",
    synergies: [{ skill: "charged-bolt", bonus: "+damage per level" }],
    synergyFor: ["chain-lightning", "nova", "thunder-storm"],
    mechanics: [
      "Uses the slower Lightning cast animation, not the standard Sorceress one. Plan Faster Cast Rate against the lightning breakpoint table.",
    ],
    confidence: "verified",
  },
  {
    slug: "chain-lightning",
    name: "Chain Lightning",
    classSlug: "sorceress",
    tree: "lightning-spells",
    kind: "spell",
    element: "lightning",
    requiredLevel: 18,
    prerequisites: ["lightning"],
    summary: "A bolt that jumps between nearby enemies. The main Lightning Sorceress clear skill.",
    synergies: [
      { skill: "charged-bolt", bonus: "+damage per level" },
      { skill: "lightning", bonus: "+damage per level" },
    ],
    mechanics: [
      "Also uses the slower Lightning cast animation.",
    ],
    confidence: "verified",
  },
  {
    slug: "teleport",
    name: "Teleport",
    classSlug: "sorceress",
    tree: "lightning-spells",
    kind: "spell",
    element: "magic",
    requiredLevel: 18,
    prerequisites: ["telekinesis"],
    summary:
      "Instantly move to any visible point. The single most valuable skill in Diablo II.",
    manaCost: "Moderate, and reduced by skill level",
    mechanics: [
      "One point is all any build needs. Extra points only reduce the mana cost.",
      "Passes through walls and monsters, which is what makes Sorceress farming routes so fast.",
      "Teleport speed is governed by Faster Cast Rate — this is why 105% FCR matters so much.",
      "Every other class needs an Enigma runeword to do this. The Sorceress gets it at level 18 for one point.",
    ],
    confidence: "verified",
  },
  {
    slug: "thunder-storm",
    name: "Thunder Storm",
    classSlug: "sorceress",
    tree: "lightning-spells",
    kind: "buff",
    element: "lightning",
    requiredLevel: 24,
    prerequisites: ["chain-lightning", "nova"],
    summary: "A timed buff that periodically strikes a random nearby enemy with lightning.",
    synergies: [{ skill: "lightning", bonus: "+damage per level" }],
    mechanics: [
      "Stacks with a cold armor and with Energy Shield — they are not mutually exclusive.",
    ],
    confidence: "verified",
  },
  {
    slug: "energy-shield",
    name: "Energy Shield",
    classSlug: "sorceress",
    tree: "lightning-spells",
    kind: "buff",
    element: "magic",
    requiredLevel: 24,
    prerequisites: ["chain-lightning", "teleport"],
    summary: "Diverts a portion of incoming damage to mana instead of life.",
    mechanics: [
      "Powerful but demanding: it needs a large mana pool and mana-per-damage efficiency from skill levels to be worth the investment.",
      "Most Blizzard and Fire Sorceresses skip it entirely and put the points into life instead.",
    ],
    confidence: "verified",
  },
  {
    slug: "lightning-mastery",
    name: "Lightning Mastery",
    classSlug: "sorceress",
    tree: "lightning-spells",
    kind: "passive",
    element: "lightning",
    requiredLevel: 30,
    summary: "Increases lightning damage. Unlike Cold Mastery, this raises damage rather than piercing resistance.",
    mechanics: [
      "This is an important asymmetry: Cold Mastery lowers enemy resistance, Lightning and Fire Mastery increase your damage. They are not equivalent, and they interact very differently with immunities.",
    ],
    confidence: "verified",
  },

  // -------------------------------------------------------------------------
  // Fire
  // -------------------------------------------------------------------------
  {
    slug: "fire-bolt",
    name: "Fire Bolt",
    classSlug: "sorceress",
    tree: "fire-spells",
    kind: "spell",
    element: "fire",
    requiredLevel: 1,
    summary: "A single fire projectile. The Sorceress's default level 1 attack and a Fire Ball synergy.",
    synergyFor: ["fire-ball", "meteor", "hydra"],
    confidence: "verified",
  },
  {
    slug: "warmth",
    name: "Warmth",
    classSlug: "sorceress",
    tree: "fire-spells",
    kind: "passive",
    element: "fire",
    requiredLevel: 1,
    summary: "Increases mana regeneration. Taken by essentially every Sorceress.",
    mechanics: [
      "One point is standard. It is the cheapest mana solution in the game and it works from level 1.",
      "Even builds with an Insight mercenary usually keep the point — it costs nothing meaningful.",
    ],
    confidence: "verified",
  },
  {
    slug: "inferno",
    name: "Inferno",
    classSlug: "sorceress",
    tree: "fire-spells",
    kind: "spell",
    element: "fire",
    requiredLevel: 6,
    summary: "A short-range stream of flame. Rarely used past early Normal.",
    synergyFor: ["blaze", "fire-wall"],
    confidence: "verified",
  },
  {
    slug: "blaze",
    name: "Blaze",
    classSlug: "sorceress",
    tree: "fire-spells",
    kind: "spell",
    element: "fire",
    requiredLevel: 12,
    prerequisites: ["inferno"],
    summary: "Leaves a trail of fire behind you as you move.",
    synergies: [{ skill: "inferno", bonus: "+damage per level" }],
    confidence: "verified",
  },
  {
    slug: "fire-ball",
    name: "Fire Ball",
    classSlug: "sorceress",
    tree: "fire-spells",
    kind: "spell",
    element: "fire",
    requiredLevel: 12,
    prerequisites: ["fire-bolt"],
    summary:
      "An exploding fire projectile. The Fire Sorceress's workhorse from level 12 to the end of the game.",
    synergies: [{ skill: "fire-bolt", bonus: "+damage per level" }],
    synergyFor: ["meteor"],
    mechanics: [
      "No cooldown and good area damage, which makes it the most practical fire skill for general clearing.",
    ],
    confidence: "verified",
  },
  {
    slug: "fire-wall",
    name: "Fire Wall",
    classSlug: "sorceress",
    tree: "fire-spells",
    kind: "spell",
    element: "fire",
    requiredLevel: 18,
    prerequisites: ["blaze"],
    summary: "A burning wall on the ground. High damage to anything forced to stand in it.",
    synergies: [{ skill: "inferno", bonus: "+damage per level" }],
    confidence: "verified",
  },
  {
    slug: "enchant",
    name: "Enchant",
    classSlug: "sorceress",
    tree: "fire-spells",
    kind: "buff",
    element: "fire",
    requiredLevel: 18,
    prerequisites: ["fire-ball", "warmth"],
    summary:
      "Adds fire damage to a target's attacks. Castable on other players and on your mercenary.",
    mechanics: [
      "The basis of the Enchantress support build — she buffs an entire party's weapon damage.",
      "Also a strong quality-of-life pick for any Sorceress with a physical-damage mercenary.",
    ],
    confidence: "verified",
  },
  {
    slug: "meteor",
    name: "Meteor",
    classSlug: "sorceress",
    tree: "fire-spells",
    kind: "spell",
    element: "fire",
    requiredLevel: 24,
    prerequisites: ["fire-ball", "fire-wall"],
    summary:
      "Calls down a meteor that deals impact damage and leaves a burning patch. High damage, delayed.",
    synergies: [
      { skill: "fire-bolt", bonus: "+damage per level" },
      { skill: "fire-ball", bonus: "+damage per level" },
    ],
    mechanics: [
      "There is a delay between cast and impact. Lead your target, as with Blizzard.",
    ],
    confidence: "verified",
  },
  {
    slug: "hydra",
    name: "Hydra",
    classSlug: "sorceress",
    tree: "fire-spells",
    kind: "summon",
    element: "fire",
    requiredLevel: 30,
    prerequisites: ["enchant"],
    summary: "Summons a three-headed fire turret that attacks independently for a duration.",
    synergies: [{ skill: "fire-bolt", bonus: "+damage per level" }],
    mechanics: [
      "Fires and forgets — you can cast it and leave, which makes it unusually safe.",
    ],
    confidence: "verified",
  },
  {
    slug: "fire-mastery",
    name: "Fire Mastery",
    classSlug: "sorceress",
    tree: "fire-spells",
    kind: "passive",
    element: "fire",
    requiredLevel: 30,
    summary: "Increases fire damage. Like Lightning Mastery, this raises damage rather than piercing resistance.",
    confidence: "verified",
  },
];
