/**
 * The measurement `GOOD_AT_THRESHOLD` rests on, recomputed from the builds.
 *
 * `lib/builds/filter.ts` justified its threshold with a distribution: "across
 * the 29 published builds and eight axes — 232 ratings — 47.4% sit at 4 or
 * above". That was true when it was written. The catalogue has since reached
 * fifty-three builds, and a paragraph of statistics typed into a comment is
 * exactly the kind of claim about data this project does not allow anywhere
 * else. Rewriting "29" to "53" without measuring again would be worse than
 * leaving it: it would look current and be invented.
 *
 * So the numbers are generated. This script writes
 * `docs/measurements/rating-distribution.json`, `rating-distribution.test.ts`
 * recomputes and compares, and `docs/adr/0004-good-at-threshold.md` is where the
 * decision the numbers support is argued. The threshold moves only when the
 * evidence moves it.
 *
 * Deterministic by construction: axes in `RATING_AXES` order, rating buckets 1
 * through 5, thresholds ascending, integers and fixed-precision decimals, and
 * no timestamp anywhere. Two runs over the same content produce the same bytes.
 *
 * Regenerate with `npm run gen:rating-distribution`.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";

import { getBuilds } from "../lib/registry";
import { RATING_AXES } from "../lib/builds/filter";

/** Where the published measurement lives, relative to the repository root. */
export const ARTEFACT = join("docs", "measurements", "rating-distribution.json");

/** The candidate thresholds, in the order the ADR argues them. */
export const CANDIDATES = [3, 4, 5] as const;

export interface Distribution {
  /** What produced these numbers, for whoever opens the file first. */
  source: string;
  builds: number;
  axes: string[];
  ratings: number;
  /** How many ratings sit at each value, 1 through 5. */
  histogram: Record<string, number>;
  /** The same, per axis, so a per-axis claim can be checked against it. */
  perAxis: Record<string, Record<string, number>>;
  /** What each candidate threshold would select. */
  thresholds: Record<
    string,
    {
      qualifyingRatings: number;
      shareOfRatings: number;
      averageTagsPerBuild: number;
      buildsWithNoTag: number;
      /** Builds this axis would tag, per axis. */
      perAxis: Record<string, number>;
    }
  >;
}

const round = (value: number, places: number) => Number(value.toFixed(places));

export function measureDistribution(): Distribution {
  // en-US is the editorial source; ratings are invariant, so the locale a build
  // is read in cannot change a number here.
  const builds = getBuilds("en-us");
  const axes = [...RATING_AXES];

  const histogram: Record<string, number> = { "1": 0, "2": 0, "3": 0, "4": 0, "5": 0 };
  const perAxis: Record<string, Record<string, number>> = {};
  for (const axis of axes) {
    perAxis[axis] = { "1": 0, "2": 0, "3": 0, "4": 0, "5": 0 };
  }

  for (const build of builds) {
    for (const axis of axes) {
      const value = String(build.ratings[axis]);
      histogram[value] = (histogram[value] ?? 0) + 1;
      perAxis[axis][value] = (perAxis[axis][value] ?? 0) + 1;
    }
  }

  const ratings = builds.length * axes.length;
  const thresholds: Distribution["thresholds"] = {};
  for (const threshold of CANDIDATES) {
    let qualifying = 0;
    let noTag = 0;
    const byAxis: Record<string, number> = {};
    for (const axis of axes) byAxis[axis] = 0;
    for (const build of builds) {
      let tags = 0;
      for (const axis of axes) {
        if (build.ratings[axis] >= threshold) {
          tags++;
          byAxis[axis]++;
        }
      }
      qualifying += tags;
      if (tags === 0) noTag++;
    }
    thresholds[String(threshold)] = {
      qualifyingRatings: qualifying,
      shareOfRatings: round(qualifying / ratings, 4),
      averageTagsPerBuild: round(qualifying / builds.length, 2),
      buildsWithNoTag: noTag,
      perAxis: byAxis,
    };
  }

  return {
    source: "Generated by scripts/rating-distribution.ts — do not edit by hand.",
    builds: builds.length,
    axes,
    ratings,
    histogram,
    perAxis,
    thresholds,
  };
}

/** The exact bytes the artefact holds, so the gate compares text to text. */
export function serialise(distribution: Distribution): string {
  return `${JSON.stringify(distribution, null, 2)}\n`;
}

// Written only when this file is the process entry point, so the gate can
// import `measureDistribution` without the import having a side effect.
const entry = process.argv[1]?.replace(/\\/g, "/") ?? "";
if (entry.endsWith("scripts/rating-distribution.ts")) {
  const distribution = measureDistribution();
  writeFileSync(join(process.cwd(), ARTEFACT), serialise(distribution), "utf8");
  console.log(
    `Wrote ${ARTEFACT}: ${distribution.builds} builds, ${distribution.ratings} ratings.`,
  );
  for (const threshold of CANDIDATES) {
    const row = distribution.thresholds[String(threshold)];
    console.log(
      `  at ${threshold}+: ${(row.shareOfRatings * 100).toFixed(1)}% of ratings, ` +
        `${row.averageTagsPerBuild} tags per build, ${row.buildsWithNoTag} builds with none`,
    );
  }
}
