import type { Skill, SkillTree } from "@/lib/types";

/**
 * The Paladin's three skill trees and thirty skills.
 *
 * Skill names and unlock levels verified against The Arreat Summit's Paladin
 * skill pages. Blessed Hammer's synergies (Vigor and Blessed Aim, +14% magic
 * damage per level each) cross-checked against current build guides.
 *
 * Note the aura system's defining quirk: only one aura is active at a time,
 * but a maxed aura contributes its synergy bonus whether or not it is running.
 * That is why a Hammerdin maxes Blessed Aim and never activates it.
 */

export const paladinTrees: SkillTree[] = [
  {
    slug: "combat-skills",
    name: "Combat Skills",
    classSlug: "paladin",
    order: 1,
    summary: "Attacks and defensive utility, including Blessed Hammer.",
    theme:
      "Where the Paladin's actual attacks live. Blessed Hammer's magic damage is why the class is considered the strongest all-rounder in the game.",
  },
  {
    slug: "offensive-auras",
    name: "Offensive Auras",
    classSlug: "paladin",
    order: 2,
    summary: "Party-wide damage multipliers.",
    theme:
      "One aura runs at a time, and it affects your whole party. Concentration for hammers, Fanaticism for physical attacks, Conviction for elemental.",
  },
  {
    slug: "defensive-auras",
    name: "Defensive Auras",
    classSlug: "paladin",
    order: 3,
    summary: "Resistances, sustain and movement speed.",
    theme:
      "Defensive auras cover survivability and quality of life. Several are worth one point purely as a situational swap.",
  },
];

export const paladinSkills: Skill[] = [
  // -------------------------------------------------------------------------
  // Combat Skills
  // -------------------------------------------------------------------------
  {
    slug: "sacrifice",
    name: "Sacrifice",
    classSlug: "paladin",
    tree: "combat-skills",
    kind: "attack",
    element: "physical",
    requiredLevel: 1,
    summary: "A heavy attack that damages you as well as the target.",
    synergyFor: ["zeal", "vengeance"],
    confidence: "verified",
  },
  {
    slug: "smite",
    name: "Smite",
    classSlug: "paladin",
    tree: "combat-skills",
    kind: "attack",
    element: "physical",
    requiredLevel: 1,
    summary:
      "A shield bash that always hits and always stuns. The only attack in the game that cannot miss.",
    mechanics: [
      "Smite never misses — it does not roll against attack rating at all.",
      "It stuns, which is why it is the standard tool for Uber Tristram: a Smiter locks down Uber bosses that would otherwise kill anything.",
      "Damage comes from the shield, not the weapon.",
    ],
    synergyFor: ["holy-shield"],
    confidence: "verified",
  },
  {
    slug: "holy-bolt",
    name: "Holy Bolt",
    classSlug: "paladin",
    tree: "combat-skills",
    kind: "spell",
    element: "magic",
    requiredLevel: 6,
    prerequisites: ["sacrifice"],
    summary:
      "A magic bolt that damages undead and heals players. Blessed Hammer's prerequisite.",
    synergyFor: ["blessed-hammer", "fist-of-the-heavens"],
    mechanics: [
      "Damages undead only, but heals allied players it passes through — a genuinely useful party skill.",
    ],
    confidence: "verified",
  },
  {
    slug: "zeal",
    name: "Zeal",
    classSlug: "paladin",
    tree: "combat-skills",
    kind: "attack",
    element: "physical",
    requiredLevel: 12,
    prerequisites: ["sacrifice"],
    summary: "A chain of rapid attacks against nearby targets. The Zealot's core skill.",
    synergies: [{ skill: "sacrifice", bonus: "+damage per level" }],
    confidence: "verified",
  },
  {
    slug: "charge",
    name: "Charge",
    classSlug: "paladin",
    tree: "combat-skills",
    kind: "attack",
    element: "physical",
    requiredLevel: 12,
    prerequisites: ["might"],
    summary: "Rush a target and hit it on arrival. Doubles as cheap mobility before Enigma.",
    confidence: "verified",
  },
  {
    slug: "vengeance",
    name: "Vengeance",
    classSlug: "paladin",
    tree: "combat-skills",
    kind: "attack",
    element: "physical",
    requiredLevel: 18,
    prerequisites: ["zeal"],
    summary:
      "Converts a portion of physical damage into fire, cold and lightning simultaneously.",
    mechanics: [
      "Because it deals all three elements at once, it is the classic answer to physical immunity — the Avenger build is built entirely on this.",
    ],
    confidence: "verified",
  },
  {
    slug: "blessed-hammer",
    name: "Blessed Hammer",
    classSlug: "paladin",
    tree: "combat-skills",
    kind: "spell",
    element: "magic",
    requiredLevel: 18,
    prerequisites: ["holy-bolt"],
    summary:
      "A hammer that spirals outward dealing magic damage. Almost nothing in the game resists it.",
    synergies: [
      { skill: "vigor", bonus: "+14% magic damage per level" },
      { skill: "blessed-aim", bonus: "+14% magic damage per level" },
    ],
    mechanics: [
      "Deals **magic** damage. Only a handful of monsters in Acts 2 and 3 are magic immune, which is the single biggest reason this build is considered the strongest all-rounder.",
      "Deals 150% damage to Undead and Demons, which is most of what you fight in Chaos Sanctuary and Baal runs.",
      "**It spirals, it does not fly straight.** Hammers travel in an expanding clockwise spiral starting around the 9 o'clock position. New Hammerdins report the build feeling weak — they are missing.",
      "Concentration multiplies its damage directly while active.",
    ],
    confidence: "verified",
  },
  {
    slug: "conversion",
    name: "Conversion",
    classSlug: "paladin",
    tree: "combat-skills",
    kind: "attack",
    element: "magic",
    requiredLevel: 24,
    prerequisites: ["zeal", "holy-bolt"],
    summary: "Temporarily turns a monster into an ally that fights for you.",
    confidence: "verified",
  },
  {
    slug: "holy-shield",
    name: "Holy Shield",
    classSlug: "paladin",
    tree: "combat-skills",
    kind: "buff",
    element: "magic",
    requiredLevel: 24,
    prerequisites: ["smite"],
    summary:
      "A timed buff granting large defence and block chance. Every Paladin build takes it.",
    synergies: [{ skill: "smite", bonus: "+damage per level" }],
    mechanics: [
      "The block bonus is what lets a Paladin reach and hold maximum block, which is the class's main survivability advantage.",
      "One hard point is usually enough — +skills gear pushes its effective level well past that.",
    ],
    confidence: "verified",
  },
  {
    slug: "fist-of-the-heavens",
    name: "Fist of the Heavens",
    classSlug: "paladin",
    tree: "combat-skills",
    kind: "spell",
    element: "lightning",
    requiredLevel: 30,
    prerequisites: ["blessed-hammer", "holy-shield"],
    summary: "A lightning bolt plus radiating holy bolts. Lightning and magic damage together.",
    synergies: [{ skill: "holy-bolt", bonus: "+damage per level" }],
    confidence: "verified",
  },

  // -------------------------------------------------------------------------
  // Offensive Auras
  // -------------------------------------------------------------------------
  {
    slug: "might",
    name: "Might",
    classSlug: "paladin",
    tree: "offensive-auras",
    kind: "aura",
    element: "physical",
    requiredLevel: 1,
    summary: "Increases physical damage for you and your party.",
    synergyFor: ["blessed-aim", "concentration", "fanaticism"],
    confidence: "verified",
  },
  {
    slug: "holy-fire",
    name: "Holy Fire",
    classSlug: "paladin",
    tree: "offensive-auras",
    kind: "aura",
    element: "fire",
    requiredLevel: 6,
    prerequisites: ["might"],
    summary: "Adds fire damage to attacks and burns nearby enemies.",
    confidence: "verified",
  },
  {
    slug: "thorns",
    name: "Thorns",
    classSlug: "paladin",
    tree: "offensive-auras",
    kind: "aura",
    element: "physical",
    requiredLevel: 6,
    prerequisites: ["might"],
    summary: "Returns a portion of melee damage to the attacker.",
    confidence: "verified",
  },
  {
    slug: "blessed-aim",
    name: "Blessed Aim",
    classSlug: "paladin",
    tree: "offensive-auras",
    kind: "aura",
    element: "physical",
    requiredLevel: 12,
    prerequisites: ["might"],
    summary:
      "Increases attack rating. On a Hammerdin it is maxed purely as a synergy and never activated.",
    synergyFor: ["blessed-hammer"],
    mechanics: [
      "This is the clearest example of the aura system's quirk: a maxed aura contributes its synergy bonus whether or not it is the active aura.",
    ],
    confidence: "verified",
  },
  {
    slug: "concentration",
    name: "Concentration",
    classSlug: "paladin",
    tree: "offensive-auras",
    kind: "aura",
    element: "physical",
    requiredLevel: 18,
    prerequisites: ["blessed-aim"],
    summary:
      "Increases damage and prevents interruption. The Hammerdin's active aura.",
    mechanics: [
      "Multiplies Blessed Hammer's magic damage directly — it is not a synergy, it is a live multiplier, and it must be the aura you are running.",
      "Also gives a chance to avoid being interrupted while attacking or casting.",
    ],
    confidence: "verified",
  },
  {
    slug: "holy-freeze",
    name: "Holy Freeze",
    classSlug: "paladin",
    tree: "offensive-auras",
    kind: "aura",
    element: "cold",
    requiredLevel: 18,
    prerequisites: ["holy-fire"],
    summary:
      "Chills everything nearby, slowing attacks and movement. The strongest defensive aura in the game.",
    mechanics: [
      "Slowing everything around you is worth more than raw defence in Hell, which is why it is the default Hardcore mercenary aura.",
    ],
    confidence: "verified",
  },
  {
    slug: "holy-shock",
    name: "Holy Shock",
    classSlug: "paladin",
    tree: "offensive-auras",
    kind: "aura",
    element: "lightning",
    requiredLevel: 24,
    prerequisites: ["holy-freeze"],
    summary: "Adds lightning damage to attacks. The core of the Holy Shock Zealot.",
    confidence: "verified",
  },
  {
    slug: "sanctuary",
    name: "Sanctuary",
    classSlug: "paladin",
    tree: "offensive-auras",
    kind: "aura",
    element: "magic",
    requiredLevel: 24,
    prerequisites: ["holy-freeze"],
    summary: "Damages and knocks back undead, and ignores their physical resistance.",
    confidence: "verified",
  },
  {
    slug: "fanaticism",
    name: "Fanaticism",
    classSlug: "paladin",
    tree: "offensive-auras",
    kind: "aura",
    element: "physical",
    requiredLevel: 30,
    prerequisites: ["concentration"],
    summary:
      "Increases attack speed, attack rating and damage. The best physical-attack aura in the game.",
    mechanics: [
      "The attack speed bonus applies to your whole party, which is why a Fanaticism Paladin is so valuable in a group.",
      "Worth one point on almost any Paladin as a situational swap.",
    ],
    confidence: "verified",
  },
  {
    slug: "conviction",
    name: "Conviction",
    classSlug: "paladin",
    tree: "offensive-auras",
    kind: "aura",
    element: "magic",
    requiredLevel: 30,
    prerequisites: ["holy-shock", "sanctuary"],
    summary:
      "Lowers enemy fire, cold and lightning resistance, and their defence. The aura the Infinity runeword grants.",
    mechanics: [
      "This is the same aura an Infinity runeword provides, which is why Infinity is so transformative for elemental casters.",
      "It reduces fire, cold and lightning resistance — not poison, and not magic.",
    ],
    confidence: "verified",
  },

  // -------------------------------------------------------------------------
  // Defensive Auras
  // -------------------------------------------------------------------------
  {
    slug: "prayer",
    name: "Prayer",
    classSlug: "paladin",
    tree: "defensive-auras",
    kind: "aura",
    requiredLevel: 1,
    summary: "Regenerates life for you and your party.",
    synergyFor: ["cleansing", "meditation", "redemption"],
    confidence: "verified",
  },
  {
    slug: "resist-fire",
    name: "Resist Fire",
    classSlug: "paladin",
    tree: "defensive-auras",
    kind: "aura",
    element: "fire",
    requiredLevel: 1,
    summary: "Raises fire resistance, and the maximum fire resistance cap.",
    mechanics: [
      "The maximum-resistance increase is the valuable part — it raises the 75% cap itself.",
    ],
    confidence: "verified",
  },
  {
    slug: "resist-cold",
    name: "Resist Cold",
    classSlug: "paladin",
    tree: "defensive-auras",
    kind: "aura",
    element: "cold",
    requiredLevel: 6,
    prerequisites: ["resist-fire"],
    summary: "Raises cold resistance and its maximum.",
    confidence: "verified",
  },
  {
    slug: "defiance",
    name: "Defiance",
    classSlug: "paladin",
    tree: "defensive-auras",
    kind: "aura",
    requiredLevel: 6,
    prerequisites: ["prayer"],
    summary: "Increases defence for you and your party.",
    synergyFor: ["holy-shield", "vigor"],
    confidence: "verified",
  },
  {
    slug: "resist-lightning",
    name: "Resist Lightning",
    classSlug: "paladin",
    tree: "defensive-auras",
    kind: "aura",
    element: "lightning",
    requiredLevel: 12,
    prerequisites: ["resist-cold"],
    summary: "Raises lightning resistance and its maximum.",
    mechanics: [
      "Frequently maxed last on a Hammerdin specifically for the maximum lightning resistance, which is what makes Uber Mephisto's Conviction survivable.",
    ],
    confidence: "verified",
  },
  {
    slug: "cleansing",
    name: "Cleansing",
    classSlug: "paladin",
    tree: "defensive-auras",
    kind: "aura",
    requiredLevel: 12,
    prerequisites: ["prayer"],
    summary: "Reduces the duration of curses and poison on you and your party.",
    synergies: [{ skill: "prayer", bonus: "+effect per level" }],
    confidence: "verified",
  },
  {
    slug: "vigor",
    name: "Vigor",
    classSlug: "paladin",
    tree: "defensive-auras",
    kind: "aura",
    requiredLevel: 18,
    prerequisites: ["defiance"],
    summary:
      "Increases movement speed and stamina recovery. Also a Blessed Hammer synergy.",
    synergyFor: ["blessed-hammer"],
    mechanics: [
      "Doubles as one of Blessed Hammer's two synergies at +14% magic damage per level, so a Hammerdin maxes it regardless of whether the movement speed is wanted.",
    ],
    confidence: "verified",
  },
  {
    slug: "meditation",
    name: "Meditation",
    classSlug: "paladin",
    tree: "defensive-auras",
    kind: "aura",
    requiredLevel: 24,
    prerequisites: ["cleansing"],
    summary:
      "Rapidly regenerates mana for you and your party. The aura the Insight runeword grants.",
    mechanics: [
      "This is the same aura Insight provides, which is why a single cheap runeword on a mercenary permanently solves caster mana.",
    ],
    confidence: "verified",
  },
  {
    slug: "redemption",
    name: "Redemption",
    classSlug: "paladin",
    tree: "defensive-auras",
    kind: "aura",
    requiredLevel: 30,
    prerequisites: ["meditation"],
    summary:
      "Consumes nearby corpses to restore life and mana. One of the best sustain tools in the game.",
    mechanics: [
      "Switching to Redemption for a moment after clearing a pack refills life and mana entirely. Worth one point on every Paladin.",
      "It also destroys corpses, which matters if a party member relies on them.",
    ],
    confidence: "verified",
  },
  {
    slug: "salvation",
    name: "Salvation",
    classSlug: "paladin",
    tree: "defensive-auras",
    kind: "aura",
    requiredLevel: 30,
    prerequisites: ["resist-lightning", "vigor"],
    summary: "Raises fire, cold and lightning resistance for you and your party.",
    confidence: "verified",
  },
];
